baseURL = "https://rahmathidayat.my.id"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Rahmat Hidayat"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-134956300-2"
disqusShortname = "yourdiscussshortname"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "A Librarian, Software Engineer (recently using Go, PHP, JS), Creative Thinker. Instagram @zhorahmat"
  homeMetaContent = "A Librarian, Software Engineer (recently using Go, PHP, JS), Creative Thinker. Instagram @zhorahmat"
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "daengrahmat"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
